# **NUMPY FOUNDATIONS**

##BASIC FUNCTIONS

In [99]:
# Importing numpy as np , np is just a shortform which we will use in the notebook instead of writing "numpy"
import numpy as np

In [100]:
# How 1D array is made using numpy:
array_1d = np.array([1,2,3,4])
print(f"array_1d looks like: {array_1d}")
print(f"dtype of array_1d: {type(array_1d)}")

array_1d looks like: [1 2 3 4]
dtype of array_1d: <class 'numpy.ndarray'>


In [101]:
# 2D and 3D arrays using np
array_2d = np.array([[1,2],[3,4]])
print(f"array_2d looks like:\n{array_2d}")
print(f"dtype of array_2d: {type(array_2d)}. Same as array_1d")

array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,2]]])
print(f"array_3d looks like:\n{array_3d}")
print(f"dtype of array_3d: {type(array_3d)}. Same as array_1d")


array_2d looks like:
[[1 2]
 [3 4]]
dtype of array_2d: <class 'numpy.ndarray'>. Same as array_1d
array_3d looks like:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 2]]]
dtype of array_3d: <class 'numpy.ndarray'>. Same as array_1d


In [102]:
# np.arange function -> works like range function which require 2 values , 1st value is included and 2nd is exclused in output array.
print("printing the output without storing it in variable:")
np.arange(1,11)

printing the output without storing it in variable:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
print("After storing it in arange_variable:")
arange_variable = np.arange(1,11)
print (f"arange_variable:\n {arange_variable}")
print("See, 1 is included in array but 11 is excluded, number before 11 is included.")

After storing it in arange_variable:
arange_variable:
 [ 1  2  3  4  5  6  7  8  9 10]
See, 1 is included in array but 11 is excluded, number before 11 is included.


In [104]:
# using dtype
np.arange(1,11,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [105]:
# arange with steps
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [106]:
# arange with single value (it starts with 0 when positive number and [] when single negative value is given)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [108]:
# with reshape -> .reshape() helps in reshaping the numpy array with valid input. If input for .reshape is (3,3) it means reshaping array in 3x3 array or matrix.
# np.arange(1,11) include 10 values, using reshape function we can reshape the array in (2,5)...(5,2)... but we can't reshape it as (3,4)
# because 3x4 matrix include 12 values and here we have only 10.
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [109]:
# arange with reshape example
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [110]:
"""Initialising Array using np.zeros , np.ones and np.random"""

# np.ones and np.zeros
# np.ones need shape as input OR here, we provide the 'tuple'
ones_variable = np.ones((2,3))
print(f"ones_variable:\n{ones_variable}\n")

zeros_variable = np.zeros((4,5))
print(f"zeros_variable:\n{zeros_variable}\n")

print("USECASE: intializing weights in neural networks")

ones_variable:
[[1. 1. 1.]
 [1. 1. 1.]]

zeros_variable:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

USECASE: intializing weights in neural networks


In [111]:
# np.random -> initialize with random values between 0 and 1
np.random.random((3,4))

# why two randoms? -> because random is a class and it has a method named random ( concept of OOPS )

array([[0.08568674, 0.78904836, 0.647584  , 0.64511415],
       [0.56073148, 0.54762569, 0.51038902, 0.27264894],
       [0.83362765, 0.97749386, 0.15941179, 0.58604688]])

In [112]:
# np.linspace -> helps in generating the values within a range where lowerbound and upperbound are inclusive/included.
# ALSO, all the elements generated are linearly gapped
# np.linspace(lowerbound, upperbound, number of elements)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [113]:
# np.identity -> helps creating identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##ARRAY ATTRIBUTES:
We know that every np array is a object of numpy class.
So, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on

In [114]:
# creating 3 arrays for further use
# a1 is a array/vector , a2 is a matrix , a3 is like a tensor or 3D tensor
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [115]:
# printing the a1,a2,a3
print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")
print(f"a3:\n{a3}\n")

a1:
[0 1 2 3 4 5 6 7 8 9]

a2:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

a3:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [116]:
# ndim -> tells the dimension of array
print(f"dimension of a1: {a1.ndim}")
print(f"dimension of a2: {a2.ndim}")
print(f"dimension of a3: {a3.ndim}")

dimension of a1: 1
dimension of a2: 2
dimension of a3: 3


In [117]:
# np.shape -> tells the shape in array

print(f"shape of a1: {a1.shape}")
print(f"shape of a2: {a2.shape}")
print(f"shape of a3: {a3.shape}")

# shape of a1: (10,) means we have 10 items in single direction
# shape of a2: (3, 4) means we have 3 rows and 4 columns
# shape of a3: (2, 2, 2) means there are two 2D arrays of shape 2,2

shape of a1: (10,)
shape of a2: (3, 4)
shape of a3: (2, 2, 2)


In [118]:
# size -> tells how many items
print(f"size of a1: {a1.size}")
print(f"size of a2: {a2.size}")
print(f"size of a3: {a3.size}")

size of a1: 10
size of a2: 12
size of a3: 8


In [119]:
# itemsize -> how much space array is occupying in memory and give output in bytes
# a2 a3 both gave the result '8' because integer and float value usually holds 8bytes in memory (in google colab , both int64(by default) and float hold same size)
# if i change it to int32, it will give 4 as output
print(f"itemsize of a1: {a1.itemsize}")
print(f"itemsize of a2: {a2.itemsize}")
print(f"itemsize of a3: {a3.itemsize}")


print("\nNOTE:int32 take 4bytes and int64 take 8bytes")

itemsize of a1: 4
itemsize of a2: 8
itemsize of a3: 8

NOTE:int32 take 4bytes and int64 take 8bytes


In [120]:
# dtype
print(f"dtype of a1: {a1.dtype}")
print(f"dtype of a2: {a2.dtype}")
print(f"dtype of a3: {a3.dtype}")

dtype of a1: int32
dtype of a2: float64
dtype of a3: int64


##CHANGING DATATYPES

In [121]:
# astype -> change the datatype
a3.astype(np.int32)

# USECASE: we have created an array of float dtype but that array is for storing age so you can change dtype to int32(int64 take much bigger space which we dont need)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

##ARRAY OPERATIONS

In [125]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(f"a1:\n{a1}\n")
print(f"a2:\n{a2}\n")

a1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



###Scalar Operations

In [129]:
# we can do these arithematic operations like + , - , * , / , % modulus , ** power etc...
# example of multiplication
print(a1 * 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


###Relational Operations

In [132]:
# using relational operators like > < >= <= etc... and it give output as true false
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [136]:
a2 == 22

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

###Vector Operations

In [139]:
# Vector operations: doing operations on two arrays
# a1 + a2 possible because of same shape
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [140]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

##Array Functions

In [143]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[46., 72., 69.],
       [78., 39., 71.],
       [20., 22., 92.]])

In [146]:
# We will try to cover all the important mathematical functions , we don't need to cover all of them.

# min/max/sum/prod
# min -> give smallest element of array , max -> give largest element , sum sums all the elements , prod multiply all the elements
print(f"max of a1: {np.max(a1)}\n")
print(f"min of a1: {np.min(a1)}\n")
print(f"sum of a1: {np.sum(a1)}\n")
print(f"prod of a1: {np.prod(a1)}\n")

max of a1: 92.0

min of a1: 20.0

sum of a1: 509.0

prod of a1: 1998009188398080.0



In [153]:
# max/min but for each column ( use axis = 0 ) and rows ( use axis = 1)
# this axis thing is applicable to every function
np.max(a1, axis = 0)

array([78., 72., 92.])

In [151]:
np.max(a1,axis = 1)

array([72., 78., 92.])

In [155]:
# mean/median/std/var
print(f"mean of a1: {np.mean(a1)}\n")
print(f"median of a1: {np.median(a1)}\n")
print(f"std of a1: {np.std(a1)}\n")
print(f"var of a1: {np.var(a1)}\n")

mean of a1: 56.55555555555556

median of a1: 69.0

std of a1: 24.194173362430842

var of a1: 585.3580246913581



In [157]:
# trignometric fucntions ( we dont use it very often )
np.sin(a1)

array([[ 0.90178835,  0.25382336, -0.11478481],
       [ 0.51397846,  0.96379539,  0.95105465],
       [ 0.91294525, -0.00885131, -0.77946607]])

In [168]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(f"a2 vector:\n{a2}\n")
print(f"a3 vector:\n{a3}\n")

# Dot product condition satisfied! a2 of shape 3,4 and a3 of shape 4,3
a4 = np.dot(a2,a3)
print(f"dot product of a2 and a3:\n{a4}.\n\nShape of a4 is {np.shape(a4)}")

a2 vector:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3 vector:
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

dot product of a2 and a3:
[[114 120 126]
 [378 400 422]
 [642 680 718]].

Shape of a4 is (3, 3)


In [172]:
# log and exponents
print(np.log(a1))
print()
print(np.exp(a1))

[[3.8286414  4.27666612 4.2341065 ]
 [4.35670883 3.66356165 4.26267988]
 [2.99573227 3.09104245 4.52178858]]

[[9.49611942e+19 1.85867175e+31 9.25378173e+29]
 [7.49841700e+33 8.65934004e+16 6.83767123e+30]
 [4.85165195e+08 3.58491285e+09 9.01762841e+39]]


In [175]:
# round / floor / ceil
np.round((np.random.random((2,3))*100))

array([[27., 41., 67.],
       [65., 96., 91.]])